Repository Toxa-man/labWorks_8373_2018, pull requests merged in 2018-11, with the labels that each got.

#83 [DEFENSE]KrotovaEY_lab2
  KrotovaEY/lab_2/Source.cpp
Labels: Defense

#87 TerletskayaJE_lab2
  TerletskayaJE/lab_2/lab_2.cpp
Labels: Ready

#124 KrotovaEY_lab3
  KrotovaEY/lab_3/Source.cpp
Labels: Ready

#121 OreshkoJA_lab4
  OreshkoJA/lab_4/Lab_4.cpp
Labels: Defense, Ready

#136 GusevKA_about.txt
  GusevKA/about.txt
Labels: Ready

#145 ShvetsovAM_lab4
  ShvetsovAM/lab_4/lab_4.cpp
Labels: Ready

#132 OreshkoJA_lab3
  OreshkoJA/lab_3/Лаба3.cpp
Labels: Ready

#47 VazhovIA_lab1
  VazhovIA/lab1/main.cpp
Labels: Ready
