Repository Toxa-man/labWorks_8373_2018, pull requests merged in 2018-12, with the labels that each got.

#173 ShvetsovAM_lab5
  ShvetsovAM/lab_5/Source.cpp
Labels: Ready

#175 SOKOLOVADD_lab5
  lab_5/lab_5.cpp
Labels: Ready

#170 VazhovIA_lab5
  VazhovIA/lab_5/main.cpp
Labels: Ready

#140 KrotovaEY_lab4
  KrotovaEY/lab_4/Source.cpp
Labels: Ready

#126 CyganovGS_lab3
  CyganovGS/about.txt
  CyganovGS/lab_1/lab1.cpp
  CyganovGS/lab_3/lab3.cpp
Labels: Ready

#125 TarapataSS_lab4
  TarapataSS/lab_4/ConsoleApplication15.cpp
Labels: Ready

#50 NikitinAV_lab1
  NikitinAV/about.txt
  NikitinAV/lab_1/main.cpp
Labels: Ready

#27 Creator folder
  MoskofidiAA/About.txt
Labels: Ready

#149 KrotovaEY_lab5
  KrotovaEY/lab_5/Source.cpp
Labels: Ready

#174 SOKOLOVADD_lab4
  lab_4/lab_4.cpp
Labels: Defense

#130 TarapataSS_lab2
  TarapataSS/lab_2/ConsoleApplication3.cpp
Labels: Defense

#180 SokolovaDD_lab4
  SokolovaDD/lab_4/lab_4.cpp
Labels: Ready

#179 SokolovaDD_lab5
  SokolovaDD/lab_5/lab_5.cpp
Labels: Ready

#168 IngerML_lab4
  IngerML/lab_4/main.cpp
Labels: Ready

#159 RychenkovAD_lab2
  RychenkovAD/lab_2/Source.cpp
Labels: Defense, Ready

#129 SaluyanovDE_lab4
  SaluyanovDE/lab_4/lab_4.cpp
Labels: Ready

#190 CyganovGS lab1
  CyganovGS/lab_1/lab1.cpp
Labels: Ready

#192 about
  PuerovAG/about.txt
Labels: Ready

#160 OreshkoJA_lab5
  OreshkoJA/lab_5/Lab_5.cpp
Labels: Ready

#172 SaluyanovDE_lab5
  SaluyanovDE/lab_5/lab_5.cpp
Labels: Defense

#80 VazhovIA_lab2
  VazhovIA/lab_2/main.cpp
Labels: Defense

#209 TimofeevaAI_lab5
  TimofeevaAI/lab_5/Source.cpp
Labels: Ready

#208 CyganovGS_lab5
  CyganovGS/about.txt
  CyganovGS/lab_1/lab1.cpp
  CyganovGS/lab_5/lab5.cpp
Labels: Ready

#203 EvseevSD_lab2
  EvseevSD/Project1/Debug/KalkulyaThor.exe
  EvseevSD/Project1/Debug/KalkulyaThor.ilk
  EvseevSD/Project1/Debug/KalkulyaThor.pdb
  EvseevSD/Project1/Debug/Lab1.exe
  EvseevSD/Project1/Debug/Lab1.ilk
  EvseevSD/Project1/Debug/Lab1.pdb
  EvseevSD/Project1/Debug/Project1.exe
  EvseevSD/Project1/Debug/Project1.ilk
  EvseevSD/Project1/Debug/Project1.pdb
  EvseevSD/Project1/Lab1.sln
  EvseevSD/Project1/Project1/Debug/Kalk1.obj
  EvseevSD/Project1/Project1/Debug/KalkulyaThor.tlog/CL.command.1.tlog
  EvseevSD/Project1/Project1/Debug/KalkulyaThor.tlog/CL.read.1.tlog
  EvseevSD/Project1/Project1/Debug/KalkulyaThor.tlog/CL.write.1.tlog
  EvseevSD/Project1/Project1/Debug/KalkulyaThor.tlog/KalkulyaThor.lastbuildstate
  EvseevSD/Project1/Project1/Debug/KalkulyaThor.tlog/link.command.1.tlog
  EvseevSD/Project1/Project1/Debug/KalkulyaThor.tlog/link.read.1.tlog
  EvseevSD/Project1/Project1/Debug/KalkulyaThor.tlog/link.write.1.tlog
  EvseevSD/Project1/Project1/Debug/Lab1.obj
  EvseevSD/Project1/Project1/Debug/Lab1.tlog/CL.command.1.tlog
  EvseevSD/Project1/Project1/Debug/Lab1.tlog/CL.read.1.tlog
  EvseevSD/Project1/Project1/Debug/Lab1.tlog/CL.write.1.tlog
  EvseevSD/Project1/Project1/Debug/Lab1.tlog/Lab1.lastbuildstate
  EvseevSD/Project1/Project1/Debug/Lab1.tlog/link.command.1.tlog
  EvseevSD/Project1/Project1/Debug/Lab1.tlog/link.read.1.tlog
  EvseevSD/Project1/Project1/Debug/Lab1.tlog/link.write.1.tlog
  EvseevSD/Project1/Project1/Debug/Project1.log
  EvseevSD/Project1/Project1/Debug/Project1.tlog/CL.command.1.tlog
  EvseevSD/Project1/Project1/Debug/Project1.tlog/CL.read.1.tlog
  EvseevSD/Project1/Project1/Debug/Project1.tlog/CL.write.1.tlog
  EvseevSD/Project1/Project1/Debug/Project1.tlog/Project1.lastbuildstate
  EvseevSD/Project1/Project1/Debug/Project1.tlog/link.command.1.tlog
  EvseevSD/Project1/Project1/Debug/Project1.tlog/link.read.1.tlog
  EvseevSD/Project1/Project1/Debug/Project1.tlog/link.write.1.tlog
  EvseevSD/Project1/Project1/Debug/Source.obj
  EvseevSD/Project1/Project1/Debug/kalk1.obj.enc
  EvseevSD/Project1/Project1/Debug/source.obj.enc
  EvseevSD/Project1/Project1/Debug/vc141.idb
  EvseevSD/Project1/Project1/Debug/vc141.pdb
  EvseevSD/Project1/Project1/Lab1.cpp
  EvseevSD/Project1/Project1/Project1.vcxproj
  EvseevSD/Project1/Project1/Project1.vcxproj.filters
  EvseevSD/Project1/Project1/Project1.vcxproj.user
  EvseevSD/lab_2.cpp
Labels: Ready

#158 RychenkovAD_lab4
  RychenkovAD/lab_4/Source.cpp
Labels: Ready

#28 [READY]
  MaiorovMS/About.txt
Labels: Ready

#242 EvseevSD_lab5
  EvseevSD/lab_5/lab5.cpp
Labels: Ready
